import dataset

model_config = {
    'mnist': {
        'dataset_fn': dataset.get_mnist, 
        'num_feature': 784, 
        'num_class': 10, 
        'num_value': 256, 
        'input_min':0, 
        'input_max':255,
        'learning_rate': 0.0001, 
        'batch_size': 128,
        'epochs': 50, 
    },
    'ptb': {
        'dataset_fn': dataset.get_ptb_ecg, 
        'num_feature': 187, 
        'num_class': 2, 
        'num_value': 256, 
        'input_min':0, 
        'input_max':1,
        'learning_rate': 0.002, 
        'batch_size': 128,
        'epochs': 50, 
        'loss_weight': [2.6, 1]
    },
    'qksd': {
        'dataset_fn': dataset.get_qksd, 
        'num_feature': 810, 
        'num_class': 2, 
        'num_value': 256, 
        'input_min':0, 
        'input_max':1,
        'learning_rate': 0.001, 
        'batch_size': 128,
        'epochs': 50, 
    },
    'har': {
        'dataset_fn': dataset.get_ucihar, 
        'num_feature': 561, 
        'num_class': 6, 
        'num_value': 256, 
        'input_min':0, 
        'input_max':255,
        'learning_rate': 0.001, 
        'batch_size': 128,
        'epochs': 50, 
    },
    'fsdd': {
        'dataset_fn': dataset.get_fsdd, 
        'num_feature': 800, 
        'num_class': 10, 
        'num_value': 256, 
        'input_min':0, 
        'input_max':1,
        'learning_rate': 0.005, 
        'batch_size': 128,
        'epochs': 50, 
    },
    'wisdm': {
        'dataset_fn': dataset.get_wisdm, 
        'num_feature': 144, 
        'num_class': 4, 
        'num_value': 256, 
        'input_min':0, 
        'input_max':1,
        'learning_rate': 0.001, 
        'batch_size': 128,
        'epochs': 50, 
        # 'loss_weight': [1.22, 3.42, 1.85, 1],
        'has_val': True 
    },
    'sthand': {
        'dataset_fn': dataset.get_st_handpose, 
        'num_feature': 128, 
        'num_class': 8, 
        'num_value': 256, 
        'input_min':0, 
        'input_max':1,
        'learning_rate': 0.003, 
        'batch_size': 128,
        'epochs': 70
    },
    'jsc': {
        'dataset_fn': dataset.get_jsc, 
        'num_feature': 32, 
        'num_class': 5, 
        'num_value': 256, 
        'input_min':0, 
        'input_max':1,
        'learning_rate': 0.002, 
        'batch_size': 2048,
        'epochs': 70
    },
    'nid': {
        'dataset_fn': dataset.get_nid, 
        'num_feature': 42, 
        'num_class': 2, 
        'num_value': 256, 
        'input_min':0, 
        'input_max':255,
        'learning_rate': 0.0001, 
        'batch_size': 128,
        'epochs': 50,
        'loss_weight': [2, 1],
    },
}
